# Generated by Django 5.1.1 on 2024-10-08 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='user_username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='user_pwd', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_map',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='user_username', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='user_email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='user_pwd', max_length=255)),
                ('tel', models.CharField(db_column='user_tel', max_length=10)),
                ('user_role', models.CharField(db_column='user_role', max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProposedText',
            fields=[
                ('text_id', models.CharField(db_column='text_id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('proposed_text', models.TextField(db_column='word_text', max_length=255)),
                ('word_class', models.SmallIntegerField(db_column='word_class', default=0)),
                ('uploaded_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proposed_t_admin_id', models.CharField(blank=True, db_column='proposed_t_admin_id', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'proposed_text',
                'managed': True,
            },
        ),
    ]
