# Generated by Django 5.1.1 on 2024-10-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedfile',
            name='proposed_text',
            field=models.ForeignKey(db_column='proposed_text_id', on_delete=django.db.models.deletion.CASCADE, to='users.proposedtext'),
        ),
        migrations.RenameField(
            model_name='proposedfile',
            old_name='proposed_text',
            new_name='text_id',
        ),
    ]
